import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DrawerMenu from "@/Components/Navigation/DrawerMenu/DrawerMenu";
import {  useState} from "react"
import TopNavigation from "@/Components/Navigation/TopNavigation/TopNavigation";
import ClientAdminToggle from "@/Components/Navigation/ClientAdminToggle/ClientAdminToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body >
        <div className="fixed overflow-hidden">
          <TopNavigation/>
        </div>
        <div className="flex flex-row justify-end z-40">
                <ClientAdminToggle/>
          </div>
        <div className="flex overflow-hidden">
        <DrawerMenu />
        </div>
        <div className="relative full flex-1 mt-34">
         <div className={inter.className}>{children}</div>
        </div>
      </body>
    </html>
  );
}
