import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DrawerMenu from "@/Components/DrawerMenu/DrawerMenu";
import {  useState} from "react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body >
        <div className="flex overflow-hidden">
        <DrawerMenu />
        </div>
      <div className="full flex-1">
      <div className={inter.className}>{children}</div>
      </div>
      </body>
    </html>
  );
}
